baseURL = "https://pi-lab.github.io/"
languageCode = "en-us"
title = "PI LAB"
theme = "tacademia.hugo"

[params.team]
    description = "The excellent graduate and undergraduate students, postdocs, faculty and staff members of our core team, alumni and collaborators."

[params.Footer]
    logo = "/img/institution.svg"

    title = "PI LAB"
    address = [
        "Department of Research",
        "The University of Research",
        "Building X, Room 123",
        "Reproducibility St., City, NN",
        "78712-1043" 
    ]

    facebook = "https://facebook.com/pi-lab"
    twitter = "https://twitter.com/pi-lab"
    github = "https://github.com/pi-lab"

[params.Footer.RelatedLinks]

    [params.Footer.RelatedLinks."Education"]
        "Psychology PHD" = "https://liberalarts.utexas.edu/psychology/graduate/phd.php"
        "Neuroscience PHD" = "https://neuroscienceinstitute.utexas.edu/PhD%20Program"
        "Computer Science PHD" = "https://www.cs.utexas.edu/graduate-program/phd-program"
    
    [params.Footer.RelatedLinks."Research"]
        "brainlife.io" = "https://brainlife.io"
        "TACC" = "IMAGING CENTER"
        "Indiana University UITS" = "https://dcops.iu.edu/"
        "NeuroscienceNetwork.org" = "https://NeuroscienceNetwork.org"

[params.Footer.Institutional]
    "Research Department" = "https://theuniversityofresearch.edu/departments/research"
    "The University of Research" = "https://theuniversityofresearch.edu/" 