baseURL = "https://pi-lab.github.io/"
languageCode = "en-us"
title = "PI LAB"
theme = "tacademia.hugo"

[menu]
[[menu.main]]
    identifier = "home"
    name = "HOME"
    url = "/"
    weight = 1
[[menu.main]]
    identifier = "research"
    name = "RESEARCH"
    url = "/research"
    weight = 2
[[menu.main]]
    identifier = "publications"
    name = "PUBLICATIONS"
    url = "/publications"
    weight = 3
[[menu.main]]
    identifier = "team"
    name = "TEAM"
    url = "/team"
    weight = 4
[[menu.main]]
    identifier = "news"
    name = "NEWS"
    url = "/news"
    weight = 5
[[menu.main]]
    identifier = "events"
    name = "EVENTS"
    url = "/events"
    weight = 6



[params.Front]
    carouselInterval = 3000

[params.Team]
    description = "The excellent graduate and undergraduate students, postdocs, faculty and staff members of our core team, alumni and collaborators."

[params.Footer]
    logo = "/img/institution.svg"
    logoLink = "https://theuniversityofresearch.edu/"

    title = "PI LAB"
    address = [
        "Department of Research",
        "The University of Research",
        "Building X, Room 123",
        "Reproducibility St., City, NN",
        "78712-1043" 
    ]

    facebook = "https://facebook.com/pi-lab"
    twitter = "https://twitter.com/pi-lab"
    github = "https://github.com/pi-lab"

    backgroundColor = "#FFF"
    textColor = "#000"
    sectionColor = "#333"

[params.Footer.RelatedLinks]

    [params.Footer.RelatedLinks."Education"]
        "Psychology PHD" = "https://theuniversityofresearch.edu/departments/psychology/phd"
        "Neuroscience PHD" = "https://theuniversityofresearch.edu/departments/neuroscience/phd"
        "Computer Science PHD" = "https://theuniversityofresearch.edu/departments/computerscience/phd"
    
    [params.Footer.RelatedLinks."Research"]
        "Research Platform" = "https://research.io"
        "Collaborators" = "https://anotherresearchinstitution.edu/"

[params.Footer.Institutional]
    "Research Department" = "https://theuniversityofresearch.edu/departments/research"
    "The University of Research" = "https://theuniversityofresearch.edu/" 