baseURL = "https://pi-lab.github.io/"
languageCode = "en-us"
title = "PI LAB"
theme = "tacademia.hugo"
logoNav = "/img/logo.svg"
[keys]
    googleMaps = "yourKey"
[[menu]]
[[menu.main]]
    indentifier = 'home'
    title= 'HOME'
    name="HOME"
    URL = '/'
    weight = 100
[[menu.main]]
    indentifier = 'research'
    title= 'RESEARCH'
    name="RESEARCH"
    URL = '/research'
    weight = 80
[[menu.main]]
    indentifier = 'publications'
    title= 'PUBLICATIONS'
    URL = '/publications'
    weight = 70
[[menu.main]]
    indentifier = 'team'
    title= 'TEAM'
    URL = '/team'
    weight = 60
[[menu.main]]
    identifier = 'news'
    title = 'News Section'
    URL = '/news'
[[menu.main]]
    identifier = 'events'
    title= 'Events'
    URL = '/events'

[params.team]
    description = "The excellent graduate and undergraduate students, postdocs, faculty and staff members of our core team, alumni and collaborators."

[params.Footer]
    logo = "/img/institution.svg"

    title = "PI LAB"
    address = [
        "Department of Research",
        "The University of Research",
        "Building X, Room 123",
        "Reproducibility St., City, NN",
        "78712-1043" 
    ]

    facebook = "https://facebook.com/pi-lab"
    twitter = "https://twitter.com/pi-lab"
    github = "https://github.com/pi-lab"

[params.Footer.RelatedLinks]

    [params.Footer.RelatedLinks."Education"]
        "Psychology PHD" = "https://liberalarts.utexas.edu/psychology/graduate/phd.php"
        "Neuroscience PHD" = "https://neuroscienceinstitute.utexas.edu/PhD%20Program"
        "Computer Science PHD" = "https://www.cs.utexas.edu/graduate-program/phd-program"
    
    [params.Footer.RelatedLinks."Research"]
        "brainlife.io" = "https://brainlife.io"
        "TACC" = "IMAGING CENTER"
        "Indiana University UITS" = "https://dcops.iu.edu/"
        "NeuroscienceNetwork.org" = "https://NeuroscienceNetwork.org"

[params.Footer.Institutional]
    "Research Department" = "https://theuniversityofresearch.edu/departments/research"
    "The University of Research" = "https://theuniversityofresearch.edu/" 